$schema: http://json-schema.org/draft-07/schema#
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle-Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: URL of the Accounts API
        title: Api Url
        type: string
      well_known_url:
        default: https://api.innohassle.ru/accounts/v0/.well-known
        description: URL of the well-known endpoint for the Accounts API
        title: Well Known Url
        type: string
      api_jwt_token:
        description: JWT token for accessing the Accounts API as a service
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  database_uri:
    description: MongoDB database settings
    examples:
    - mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin
    format: password
    title: Database Uri
    type: string
    writeOnly: true
  cors_allow_origins:
    default:
    - https://innohassle.ru
    - https://pre.innohassle.ru
    - http://localhost:3000
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed'
    items:
      type: string
    title: Cors Allow Origins
    type: array
  accounts:
    $ref: '#/$defs/Accounts'
required:
- database_uri
- accounts
title: Settings
type: object
